### ISSUE TITLE
PHP Apache module replaces OS X module

### ISSUE THREAD

**Issue by jenslind** [oddhill/oddboxen#597]
So everytime OS X updates the php version you have to reinstall php.
We should try to change the `libexec` path when building php.

**Comment by olofjohansson** [comment]
@jenslind I guess this is why the version of PHP CLI differs from the one Apache uses? And that's probably why I can't use Imagick?

In the meantime, how does one reinstall PHP in order to fix the problems mentioned?

**Comment by jenslind** [comment]
Yes thats probably why. It is fixed in this repo https://github.com/oddhill/puppet-php. So we should use that one. That puppet should also fix https://github.com/oddhill/oddboxen/issues/575

To rebuild php run:
`rm -R /opt/boxen/phpenv && boxen`
