### ISSUE TITLE
El Capitan support

### ISSUE THREAD

**Issue by jenslind** [oddhill/oddboxen#599]
Probably shouln't look into this until first RC is released. But anyways..
So far I have found issues with the following puppets:
- [x] Apache
- [x] Git
- [x] Mongodb
- [x] PHP

The git issue seems to be fixed. https://github.com/Homebrew/homebrew/pull/40532 So a bump to the latest version of the git puppet should fix that.

The apache puppet fails when it trying to change this file: `/System/Library/LaunchDaemons/org.apache.httpd.plist` it looks like the ´/System´ folder is locked in El Capitan. http://stackoverflow.com/questions/30768087/restricted-folder-files-in-os-x-el-capitan

And the mongodb probably needs a version bump of mongo. Not sure how the support for Capitan is in Mongodb atm.
**Edit:**
I bumped mongodb version to 3.0.4, https://github.com/jenslind/puppet-mongodb should work on el-capitan.

**Comment by olofjohansson** [comment]
I wonder if we actually do need that file? I don't know everything about that file, but I think that the only purpose is to start Apache. I think we should compare it to the default that's delivered with Yosemite in order to see if there are any relevant differences.

**Comment by jenslind** [comment]
Yeah I don't think we need it either. The plist file in the puppet is from mountain lion and the only difference I can see is that the `Disabled` key has been removed.
http://www.opensource.apple.com/source/apache/apache-782.1/org.apache.httpd.plist

I think it used to determine autostart of Apache? If so there should be other ways of accomplish that.

**Comment by ErikJohansson93** [comment]
It looks like this has been fixed in boxen/our-boxen. See https://github.com/boxen/our-boxen/commit/338fdeed2c52b75c1a6b5c14ffb76b3097d3649c

**Comment by jenslind** [comment]
Yes support has been added to boxen, but that has nothing to do with our puppet issues.

**Comment by jenslind** [comment]
Bumped boxen gem: f8e8108165cc671062b563fd811bbbc4f359b5a8
Bumped puppet-git: 81fefd3573b13fd1760707638d39e5e569d88dd1
Updated mongodb version: 5a60f21b71ee88f2bc915d35c97698e4453956e2 (This btw also fixes another bug with missing tools)

**Comment by jenslind** [comment]
We have an issue with PHP too. It fails on `./configure`. The problem seems to be that openssl headers are removed from el capitan. And we configure php with: `--with-openssl=/usr`. We probably just needs to install openssl with homebrew and link to correct folder in the configure script.

**Comment by jenslind** [comment]
It works. :dancer:

![clap](http://media.giphy.com/media/X1Y4IHQO04VZS/giphy.gif)
