### ISSUE TITLE
Problems after update

### ISSUE THREAD

**Issue by AdamGerthel** [oddhill/oddboxen#681]
Halloj!

Har uppdaterat Xcode, kört brew doctor/update etc men kan inte köra boxen, får detta meddelandet:

> --> Preparing to auto-update...
--> Complete! Nothing new from upstream.
rbenv: bundle: command not found

> The `bundle' command exists in these Ruby versions:
  2.0.0
  2.0.0-p451
  2.1.0
  2.1.2

> find: bin: No such file or directory
Can't run Puppet, fetching dependencies with librarian failed.

Hojta gärna till om ni vet vad det beror på

**Comment by jenslind** [comment]
https://github.com/oddhill/oddboxen#upgrading-from-1010-to-1011

> Install bundler `cd /opt/boxen/repo && sudo gem install bundler`

**Comment by AdamGerthel** [comment]
Gedank!
