### ISSUE TITLE
Place apps downloaded via cask in the applications folder

### ISSUE THREAD

**Issue by olofjohansson** [oddhill/oddboxen#686]
I saw that brewcask downloaded the apps to /usr/local somewhere, and this caused unexpected behaviors for me since I already had some of the applications downloaded to /Applications.

Is it possible to specify the download path? If so, is it a good idea to place the downloads in /Applications instead?

**Comment by jenslind** [comment]
I don't think you can change the download path, apps should be installed in `/opt/homebrew-cask` and then linked to the `Applications` folder. However there is an open issue about moving the app instead of symlinking it.
https://github.com/caskroom/homebrew-cask/issues/13201

**Comment by olofjohansson** [comment]
Interesting... In my case, I had Firefox installed previously, and when I opened it via terminal (`open -a Firefox`) that opened the version installed from brewcask. But if I opened the one in my applications folder in Finder, it complained that there already was an instance running.
