### ISSUE TITLE
Make everything a service

### ISSUE THREAD

**Issue by olofjohansson** [oddhill/oddboxen#726]
Boxen has something called services. A service seems to be an instance of something that can be enabled/disabled/restarted and so on. You can see a list of every service by running `boxen --list-services`.

Perhaps we could convert "everything" to services? This would make it possible for people to turn off stuff which they don't need at the moment, such as Apache. This will save battery life, and perhaps the planet.

**Comment by jenslind** [comment]
We are using OS X Apache. And Apache already have a tool to handle the start / stop, `apachectl`.

```
sudo apachectl start
sudo apachectl stop
```

**Comment by olofjohansson** [comment]
But there's also Solr, which is kinda hard to control.

And wouldn't it be nice if all of them were handled in the same way instead of having to keep different start/stop commands in your head?

**Comment by jenslind** [comment]
Solr and apache has now been integrated with boxen.

```
boxen --list-services
```
