### ISSUE TITLE
Use Tomcat for Apache Solr

### ISSUE THREAD

**Issue by olofjohansson** [oddhill/oddboxen#727]
This is the preferred way, and makes it possible to automatically start the Solr server when the system starts.

Should wait until #726 is closed, since that issue might make this unnecessary.

**Comment by jenslind** [comment]
https://cwiki.apache.org/confluence/display/solr/Running+Solr+on+Tomcat

**Comment by olofjohansson** [comment]
:(

What are the options? Our use case is basically that we want to control the instance easier so that it's automatically started etc.

**Comment by jenslind** [comment]
Investigating this :mag: 

I guess Puppets `Service` is just some kind of wrapper around `launchd`.
`/Library/LaunchDaemons` contains configs. Looks like our mysql puppet creates it's configs to that folder.

**Comment by olofjohansson** [comment]
Nice. Sounds like #726 might solve this then.

**Comment by jenslind** [comment]
Solr has now been added as a service.
