### ISSUE TITLE
Adopt Mandrill changes

### ISSUE THREAD

**Issue by olofjohansson** [oddhill/oddboxen#734]
We've currently configured sendmail (or postfix, don't remember) to send mails through Mandrill. There will be significant changes to Mandrill in a couple of months which means that we either need to:

a) Adopt the changes and continue using Mandrill
b) Get rid of Mandrill and find another SMTP relay
c) Skip SMTP relay altogether

IMO, **a** would be the best option if we don't need to pay for it. But it might be worth investigating **b** regardless, since there might be better options out there. Option **a** would be cleanest, but there might be problems sending mails depending on the current ISP, such as when you're on a train, using WiFi from a hotel or similar.

The outcome of this must be that we're still able to send emails from PHP applications no matter the ISP.

**Comment by jenslind** [comment]
https://sendgrid.com looks good

Should be easy to integrate.
https://sendgrid.com/docs/Integrate/Mail_Servers/postfix.html

**Comment by jenslind** [comment]
I have implemented sendgrid here: https://github.com/oddhill/oddboxen/tree/sendgrid

**Comment by olofjohansson** [comment]
@jenslind works like a charm! Although it did say something like "failed to restart postfix. exit code 1". It did work when I tried to start postfix manually though.

Perhaps the exit code is 1 because of warnings related to some unused parameters? Might be worth looking into if it breaks the postfix process during the update.

**Comment by olofjohansson** [comment]
This is fixed in ccf5e136542f985b70d1e030e3475c5947f2dd18.
